<?php

/**
 * This is the model base class for the table "trial_balance".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TrialBalance".
 *
 * Columns in table "trial_balance" available as properties of the model,
 * followed by relations of table "trial_balance" available as properties of the model.
 *
 * @property integer $id
 * @property integer $account_local_id
 * @property string $amount
 * @property integer $reporting_period_id
 *
 * @property ReportingPeriod $reportingPeriod
 */
abstract class BaseTrialBalance extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'trial_balance';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TrialBalance|TrialBalances', $n);
	}

	public static function representingColumn() {
		return 'amount';
	}

	public function rules() {
		return array(
			array('account_local_id, reporting_period_id', 'numerical', 'integerOnly'=>true),
			array('amount', 'length', 'max'=>11),
			array('account_local_id, amount, reporting_period_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, account_local_id, amount, reporting_period_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'reportingPeriod' => array(self::BELONGS_TO, 'ReportingPeriod', 'reporting_period_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'account_local_id' => Yii::t('app', 'Account Local'),
			'amount' => Yii::t('app', 'Amount'),
			'reporting_period_id' => null,
			'reportingPeriod' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('account_local_id', $this->account_local_id);
		$criteria->compare('amount', $this->amount, true);
		$criteria->compare('reporting_period_id', $this->reporting_period_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}