<?php

/**
 * This is the model base class for the table "admin_user_role".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AdminUserRole".
 *
 * Columns in table "admin_user_role" available as properties of the model,
 * followed by relations of table "admin_user_role" available as properties of the model.
 *
 * @property integer $id
 * @property string $role
 *
 * @property AdminUser[] $adminUsers
 */
abstract class BaseAdminUserRole extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'admin_user_role';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AdminUserRole|AdminUserRoles', $n);
	}

	public static function representingColumn() {
		return 'role';
	}

	public function rules() {
		return array(
			array('role', 'length', 'max'=>20),
			array('role', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, role', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'adminUsers' => array(self::HAS_MANY, 'AdminUser', 'admini_user_role_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'role' => Yii::t('app', 'Role'),
			'adminUsers' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('role', $this->role, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}