<?php

/**
 * This is the model base class for the table "account_local".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountLocal".
 *
 * Columns in table "account_local" available as properties of the model,
 * followed by relations of table "account_local" available as properties of the model.
 *
 * @property integer $id
 * @property integer $account_group_id
 * @property integer $ax_account
 * @property string $name
 *
 * @property AccountGroup $accountGroup
 */
abstract class BaseAccountLocal extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'account_local';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AccountLocal|AccountLocals', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('account_group_id, ax_account', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>200),
			array('account_group_id, ax_account, name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, account_group_id, ax_account, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'accountGroup' => array(self::BELONGS_TO, 'AccountGroup', 'account_group_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'account_group_id' => null,
			'ax_account' => Yii::t('app', 'Ax Account'),
			'name' => Yii::t('app', 'Name'),
			'accountGroup' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('account_group_id', $this->account_group_id);
		$criteria->compare('ax_account', $this->ax_account);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort'=>array('defaultOrder'=>'ax_account ASC'),
		));
	}
}