<?php

/**
 * This is the model base class for the table "reporting_period".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ReportingPeriod".
 *
 * Columns in table "reporting_period" available as properties of the model,
 * followed by relations of table "reporting_period" available as properties of the model.
 *
 * @property integer $id
 * @property string $description
 *
 * @property TrialBalance[] $trialBalances
 */
abstract class BaseReportingPeriod extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'reporting_period';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ReportingPeriod|ReportingPeriods', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('description', 'length', 'max'=>200),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'trialBalances' => array(self::HAS_MANY, 'TrialBalance', 'reporting_period_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'description' => Yii::t('app', 'Description'),
			'trialBalances' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}