<?php

/**
 * This is the model base class for the table "admin_user_company".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AdminUserCompany".
 *
 * Columns in table "admin_user_company" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $admin_user_id
 * @property integer $company_id
 *
 */
abstract class BaseAdminUserCompany extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'admin_user_company';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AdminUserCompany|AdminUserCompanies', $n);
	}

	public static function representingColumn() {
		return array(
			'admin_user_id',
			'company_id',
		);
	}

	public function rules() {
		return array(
			array('admin_user_id, company_id', 'required'),
			array('admin_user_id, company_id', 'numerical', 'integerOnly'=>true),
			array('admin_user_id, company_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'admin_user_id' => null,
			'company_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('admin_user_id', $this->admin_user_id);
		$criteria->compare('company_id', $this->company_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}