<?php

/**
 * This is the model base class for the table "company".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Company".
 *
 * Columns in table "company" available as properties of the model,
 * followed by relations of table "company" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $currency_iso3
 *
 * @property Currency $currencyIso3
 */
abstract class BaseCompany extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'company';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Company|Companies', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'length', 'max'=>500),
			array('currency_iso3', 'length', 'max'=>3),
			array('name, currency_iso3', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, currency_iso3', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'currencyIso3' => array(self::BELONGS_TO, 'Currency', 'currency_iso3'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'currency_iso3' => null,
			'currencyIso3' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('currency_iso3', $this->currency_iso3);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}